[package]
authors = ["Oli Scherer <github35764891676564198441@oli-obk.de>"]
edition = "2018"
name = "team_login"
version = "0.1.0"
[dependencies]
eyre = "*"
serde_json = "1.0.68"

[dependencies.reqwest]
features = ["blocking", "json"]
version = "0.11"

[dependencies.serde]
features = ["derive"]
version = "1.0"
